stages:
  data_ingestion:
    cmd: python src/Heart/components/Data_ingestion.py
    deps:
    - src/Heart/components/Data_ingestion.py
    - Notebook_Experiments/Data/heart.csv
    outs:
    - Artifacts/raw_data.csv
    - Artifacts/train_data.csv
    - Artifacts/test_data.csv
  data_transformation:
    cmd: python src/Heart/components/Data_transformation.py
    deps:
    - src/Heart/components/Data_transformation.py
    - Artifacts/train_data.csv
    - Artifacts/test_data.csv
    outs:
    - Artifacts/preprocessor.pkl
